"""Ajout des champs telephone et notifications_sms pour les SMS

Revision ID: a93b6e3bcc80
Revises: f065a315f196
Create Date: 2025-07-04 18:41:30.520742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93b6e3bcc80'
down_revision = 'f065a315f196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telephone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notifications_sms', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notifications_sms')
        batch_op.drop_column('telephone')

    # ### end Alembic commands ###
