"""ajout_notifications_email

Revision ID: ee74da8f5f33
Revises: a93b6e3bcc80
Create Date: 2025-07-04 19:10:24.828943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee74da8f5f33'
down_revision = 'a93b6e3bcc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_email', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notifications_email')

    # ### end Alembic commands ###
